import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[font]
size = 15

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 5

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]
