#!/bin/bash

export XDG_CONFIG_HOME="$HOME"/.config

ln -s "$PWD/alacritty/" "$XDG_CONFIG_HOME"
ln -s "$PWD/nvim/" "$XDG_CONFIG_HOME"
ln -s "$PWD/tmux/" "$XDG_CONFIG_HOME"

ln -s "$PWD/zsh/.zshrc" "$HOME"
ln -s "$PWD/zsh/.zsh_profile" "$HOME"

ln -s "$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault" "$HOME"

mkdir "$HOME"/bin

cp "$PWD/scripts/pbsql/pbsql.sh" "$HOME"/bin/pbsql

# create pgcli config directory and link config
mkdir -p "$HOME/.config/pgcli"
ln -s "$PWD/pgcli/config" "$HOME/.config/pgcli/config"

# link .gitconfig
ln -s "$PWD/.gitconfig" "$HOME"
